steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME", "."]
  # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'my-test', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME', '--region', 'us-west2']
images:
- gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME