steps:
  - name: 'docker/compose:1.28.0'
    args: ['up', '-d']
    dir: 'my-test'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_app:latest',
    'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']