steps:
  - name: 'docker/compose:1.28.0'
    args: ['up', '-d']
    dir: 'my-test'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_webapp:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --location=us-central1
      - --cluster=autopilot-cluster-1
